### ISSUE TITLE
Empty zero bytes PDF

### ISSUE THREAD

**Issue by ducho** [by-pinja/pdf-storage#77]
Hi! I'm trying to integrate your library into a project, but without success. Even though request and response are working fine, but I'm getting empty PDFs. I tried to change the PdfStorageType in the configuration to local, the html file was saved, but the pdf was not. My current config: 
```
web_pdf:
    container_name: web_pdf_storage
    image: ptcos/pdf-storage
    ports:
      - '5001:5000'
    platform: linux/amd64
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      BaseUrl: http://localhost:5000/
    volumes:
      - ../cdn/data:/data
      - ./docker/appsettings.json:/app/appsettings.json
    networks:
      - satur-proxy
 ```
appsettings.json
```
{
  "DbType": "inMemory",
  "MqType": "inMemory",
  "PdfStorageType": "inMemory",
  "LocalStorage": {
    "Folder": "/data"
  },
  "ApiAuthentication": {
    "Keys": [ "apikeyfortesting" ]
  },
  "Hangfire": {
    "AllowedIpAddresses": ["*"]
  }
}
```
response
```
array:1 [▼
  0 => array:5 [▼
    "pdfUri" => "http://localhost:5000/v1/pdf/guide/409338d8fed44790b6cdaa9946e7aac3.pdf"
    "htmlUri" => "http://localhost:5000/v1/pdf/guide/409338d8fed44790b6cdaa9946e7aac3.html"
    "id" => "409338d8fed44790b6cdaa9946e7aac3"
    "groupId" => "guide"
    "data" => []
  ]
]
```
